package com.taskify.services;

import java.util.List;

import com.taskify.dtos.UserDto;

public interface UserServices {

    UserDto createUser(UserDto userDto);

    UserDto addUserWithPasswordAutoGenerated(UserDto userDto);

    List<UserDto> getAllUsers();

    UserDto getUserById(Long id);

    UserDto getUserByEmail(String email);

    List<UserDto> getUsersByDepartment(String department);

    UserDto updateUser(UserDto givenUser);

    boolean deleteUser(Long id);

    List<UserDto> filterUsers(String department, String roleType);

}
